import type { EvergreenIdea } from "./types";

/**
 * A curated list of genuinely excellent Boston-area experiences to do with the
 * kids — the zero-maintenance backbone of "Things to Do Together". These live
 * in code (never a database you have to tend). URLs are official venue pages.
 */
export const EVERGREEN_IDEAS: EvergreenIdea[] = [
  {
    id: "eg-mos",
    title: "Museum of Science",
    venue: "Science Park, Boston",
    blurb: "Lightning shows, the planetarium, and hundreds of hands-on exhibits — an easy, joyful day whatever the weather.",
    category: "science",
    ageLabel: "All ages",
    bestFor: "A full morning or afternoon",
    url: "https://www.mos.org",
    quality: 92,
    isHistory: false,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-aquarium",
    title: "New England Aquarium",
    venue: "Central Wharf, Boston",
    blurb: "The giant ocean tank, the penguins, and the harbor seals out front — small children are spellbound.",
    category: "animals",
    ageLabel: "All ages",
    bestFor: "A half-day on the waterfront",
    url: "https://www.neaq.org",
    quality: 90,
    isHistory: false,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-uss",
    title: "USS Constitution & the Navy Yard",
    venue: "Charlestown Navy Yard",
    blurb: "Climb aboard 'Old Ironsides,' the oldest commissioned warship afloat, then explore the museum next door.",
    category: "history",
    ageLabel: "Ages 5+",
    bestFor: "A morning of history by the water",
    url: "https://ussconstitutionmuseum.org",
    quality: 88,
    isHistory: true,
    indoor: false,
    seasons: [],
  },
  {
    id: "eg-freedom-trail",
    title: "The Freedom Trail",
    venue: "Boston Common to Charlestown",
    blurb: "Follow the red line through 250 years of American history — do a stretch of it and stop for lunch along the way.",
    category: "history",
    ageLabel: "Ages 6+",
    bestFor: "A walking adventure",
    url: "https://www.thefreedomtrail.org",
    quality: 88,
    isHistory: true,
    indoor: false,
    seasons: ["spring", "summer", "fall"],
  },
  {
    id: "eg-tea-party",
    title: "Boston Tea Party Ships & Museum",
    venue: "Congress Street Bridge",
    blurb: "Toss the tea overboard in a lively, hands-on retelling of the night that sparked a revolution.",
    category: "history",
    ageLabel: "Ages 5+",
    bestFor: "An hour or two indoors",
    url: "https://www.bostonteapartyship.com",
    quality: 85,
    isHistory: true,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-childrens",
    title: "Boston Children's Museum",
    venue: "Fort Point, Boston",
    blurb: "Three floors built entirely for play and discovery — perfect for the little ones.",
    category: "museums",
    ageLabel: "Ages 1–9",
    bestFor: "A rainy-day morning",
    url: "https://bostonchildrensmuseum.org",
    quality: 86,
    isHistory: false,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-zoo",
    title: "Franklin Park Zoo",
    venue: "Dorchester, Boston",
    blurb: "Gorillas, lions, and a walk-through aviary in the middle of Frederick Law Olmsted's park.",
    category: "animals",
    ageLabel: "All ages",
    bestFor: "An outdoor half-day",
    url: "https://www.zoonewengland.org/franklin-park-zoo",
    quality: 84,
    isHistory: false,
    indoor: false,
    seasons: ["spring", "summer", "fall"],
  },
  {
    id: "eg-hmnh",
    title: "Harvard Museum of Natural History",
    venue: "Cambridge",
    blurb: "The famous glass flowers, towering dinosaurs, and rooms of minerals and beasts — endlessly curious.",
    category: "science",
    ageLabel: "All ages",
    bestFor: "A couple of hours in Cambridge",
    url: "https://hmnh.harvard.edu",
    quality: 85,
    isHistory: false,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-harbor-islands",
    title: "Boston Harbor Islands",
    venue: "Ferry from Long Wharf",
    blurb: "Take the ferry out for the day — explore a historic fort, hunt for the lighthouse, and picnic with a skyline view.",
    category: "outdoors",
    ageLabel: "All ages",
    bestFor: "A whole summer day",
    url: "https://www.bostonharborislands.org",
    quality: 87,
    isHistory: true,
    indoor: false,
    seasons: ["summer"],
  },
  {
    id: "eg-castle-island",
    title: "Castle Island & Fort Independence",
    venue: "South Boston",
    blurb: "A breezy loop around the fort, planes landing overhead, and Sullivan's for a hot dog at the end.",
    category: "outdoors",
    ageLabel: "All ages",
    bestFor: "An easy afternoon by the sea",
    url: "https://www.bostonharbornow.org/location/castle-island-fort-independence",
    quality: 80,
    isHistory: true,
    indoor: false,
    seasons: ["spring", "summer", "fall"],
  },
  {
    id: "eg-common",
    title: "Boston Common & Public Garden",
    venue: "Downtown Boston",
    blurb: "Swan Boats and the 'Make Way for Ducklings' statues in warm months; the Frog Pond for skating when it's cold.",
    category: "outdoors",
    ageLabel: "All ages",
    bestFor: "An easy stroll and a run-around",
    url: "https://www.boston.gov/parks/boston-common",
    quality: 82,
    isHistory: false,
    indoor: false,
    seasons: [],
  },
  {
    id: "eg-arboretum",
    title: "Arnold Arboretum",
    venue: "Jamaica Plain",
    blurb: "281 acres of trees to roam — spectacular in bloom and again in fall color, with gentle hills for little legs.",
    category: "outdoors",
    ageLabel: "All ages",
    bestFor: "A gentle outdoor ramble",
    url: "https://www.arboretum.harvard.edu",
    quality: 82,
    isHistory: false,
    indoor: false,
    seasons: ["spring", "fall"],
  },
  {
    id: "eg-esplanade",
    title: "The Charles River Esplanade",
    venue: "Along the Charles",
    blurb: "Bike paths, playgrounds, and the Hatch Shell — bring scooters and watch the sailboats.",
    category: "outdoors",
    ageLabel: "All ages",
    bestFor: "An open-air afternoon",
    url: "https://esplanade.org",
    quality: 80,
    isHistory: false,
    indoor: false,
    seasons: ["spring", "summer", "fall"],
  },
  {
    id: "eg-mfa",
    title: "Museum of Fine Arts",
    venue: "Fenway, Boston",
    blurb: "Mummies, armor, and family art carts — grand halls that still delight children.",
    category: "museums",
    ageLabel: "All ages",
    bestFor: "A calm indoor visit",
    url: "https://www.mfa.org",
    quality: 84,
    isHistory: false,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-gardner",
    title: "Isabella Stewart Gardner Museum",
    venue: "Fenway, Boston",
    blurb: "A Venetian palace built around a blooming courtyard — quietly magical, and kids go free.",
    category: "museums",
    ageLabel: "Ages 5+",
    bestFor: "A short, beautiful visit",
    url: "https://www.gardnermuseum.org",
    quality: 82,
    isHistory: false,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-bpl",
    title: "Boston Public Library",
    venue: "Copley Square",
    blurb: "The grand Bates Hall, the courtyard, and a wonderful children's room — a free, unhurried hour.",
    category: "history",
    ageLabel: "All ages",
    bestFor: "A quiet stop in Copley",
    url: "https://www.bpl.org",
    quality: 79,
    isHistory: true,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-mapparium",
    title: "The Mapparium",
    venue: "Mary Baker Eddy Library",
    blurb: "Walk through a three-story stained-glass globe from the inside — a genuinely unforgettable few minutes.",
    category: "museums",
    ageLabel: "Ages 5+",
    bestFor: "A short, wonder-filled visit",
    url: "https://www.marybakereddylibrary.org/project/the-mapparium",
    quality: 80,
    isHistory: false,
    indoor: true,
    seasons: [],
  },
  {
    id: "eg-fenway-tour",
    title: "Fenway Park Tour",
    venue: "Fenway, Boston",
    blurb: "Sit atop the Green Monster and walk the oldest ballpark in the majors, game or no game.",
    category: "sports",
    ageLabel: "All ages",
    bestFor: "An hour of baseball history",
    url: "https://www.mlb.com/redsox/ballpark/tours",
    quality: 84,
    isHistory: true,
    indoor: false,
    seasons: [],
  },
  {
    id: "eg-minuteman",
    title: "Minute Man National Historical Park",
    venue: "Lexington & Concord",
    blurb: "Walk the road where the Revolution began, past the North Bridge and living-history sites.",
    category: "history",
    ageLabel: "Ages 6+",
    bestFor: "A half-day just outside the city",
    url: "https://www.nps.gov/mima",
    quality: 86,
    isHistory: true,
    indoor: false,
    seasons: ["spring", "summer", "fall"],
  },
  {
    id: "eg-blue-hills",
    title: "Blue Hills Reservation",
    venue: "Milton",
    blurb: "Easy trails, a summit with a Boston view, and the Trailside Museum's native animals.",
    category: "outdoors",
    ageLabel: "All ages",
    bestFor: "A morning in the woods",
    url: "https://www.mass.gov/locations/blue-hills-reservation",
    quality: 78,
    isHistory: false,
    indoor: false,
    seasons: ["spring", "summer", "fall"],
  },
];
